"""Recommendation Report Engine (E23): short card + full, reproducible report.

Short report  = what to do, why (top-3 reasons with numbers), tax impact, what would change
                the call, AI-verification badge.
Full report   = every metric with its threshold, source and as-of time; the decision trace
                (rulebook version, each rule tried and why it failed/matched); scores & weights;
                drawdown attribution; tax lots; risks & counter-arguments; scenario; history.
"""
from __future__ import annotations

import hashlib
import math
from datetime import date, timedelta
from typing import Any

import orjson

from .rules import Decision

BULLISH = {"ADD", "ACCUMULATE"}
BEARISH = {"EXIT", "TRIM"}
DISCLAIMER = ("Analysis generated by FolioSense's rules engine for personal/family research. It is not investment advice "
              "from a SEBI-registered adviser. Verify the evidence and consider your circumstances before acting.")


def inr(v: float | None) -> str:
    if v is None:
        return "—"
    sign = "-" if v < 0 else ""
    v = abs(v)
    if v >= 1e7:
        return f"{sign}₹{v / 1e7:.2f} Cr"
    if v >= 1e5:
        return f"{sign}₹{v / 1e5:.2f} L"
    return f"{sign}₹{v:,.0f}"


def input_hash(facts: dict[str, Any], rulebook_version: str) -> str:
    # watch.days ticks daily; it matters only when it flips the rule (and so the action), not as a new input
    stable = {k: (round(v, 1) if isinstance(v, float) else v) for k, v in sorted(facts.items()) if k != "watch.days"}
    return hashlib.sha256(orjson.dumps({"facts": stable, "rulebook": rulebook_version}, option=orjson.OPT_SORT_KEYS)).hexdigest()


# Plain-language verdicts. The rules' action stays in the decision trace; what the person sees is
# one clear word plus how sure we are — and below GATE we don't tell anyone to trade.
VERDICT = {"EXIT": "Sell", "TRIM": "Sell some", "ADD": "Buy more", "ACCUMULATE": "Buy more (gradually)", "HOLD": "Hold",
           "SWITCH": "Switch", "REVIEW": "Hold · data missing", "REBALANCE": "Rebalance"}
HIGH, GATE = 0.75, 0.60
TRADES = {"EXIT", "TRIM", "ADD", "ACCUMULATE"}


def conviction(conf: float) -> str:
    return "high" if conf >= HIGH else "medium" if conf >= GATE else "low"


def _units(q: float | None, asset_type: str) -> str:
    if q is None:
        return ""
    word = "shares" if asset_type == "stock" else "units"
    return f"{q:,.0f} {word}" if asset_type in ("stock", "etf") else f"{q:,.3f} {word}"


def _half(q: float | None, asset_type: str) -> float | None:
    if q is None:
        return None
    return max(1.0, math.floor(q / 2)) if asset_type in ("stock", "etf") else round(q / 2, 3)


def do_line(action: str, level: str, sugg: dict[str, Any], asset_type: str, price: float | None) -> str:
    """One sentence: exactly what to do. Medium confidence → a smaller, decisive step, not a hedge."""
    q, v = sugg.get("quantity"), float(sugg.get("value") or 0)
    if action == "EXIT":
        if level == "high":
            return f"Sell all {_units(q, asset_type)} (≈ {inr(v)})."
        h = _half(q, asset_type)
        return f"Sell half now — {_units(h, asset_type)} (≈ {inr((h or 0) * (price or 0))}); decide on the rest at the next analysis."
    if action == "TRIM":
        if level == "high":
            return f"Sell {_units(q, asset_type)} (≈ {inr(v)})."
        h = _half(q, asset_type)
        return f"Sell {_units(h, asset_type)} now (≈ {inr((h or 0) * (price or 0))}) — half of the full trim."
    if action in ("ADD", "ACCUMULATE"):
        amt = v if level == "high" else v / 2
        units = f" (~{_units(math.floor(amt / price), asset_type)})" if price and asset_type in ("stock", "etf") and amt >= price else ""
        parts = sugg.get("tranches") or 1
        how = f", in {parts} parts on dips" if parts > 1 and level == "high" else ""
        return f"Buy ≈ {inr(amt)}{units}{how}." + ("" if level == "high" else " Start small — the signal is moderate.")
    if action == "SWITCH":
        return f"{sugg.get('note') or 'Switch'} (≈ {inr(v)})."
    if action == "REVIEW":
        return "Do nothing for now — keep holding until the missing data loads."
    if sugg.get("type") == "trail_stop" and sugg.get("stop"):
        whose = "your stop-loss" if sugg.get("source") == "yours" else "a stop-loss"
        return f"Keep holding and protect the gain: set {whose} at {inr(float(sugg['stop']))} — sell only if it closes below that (it trails the price up)."
    return "Do nothing — keep holding."


def verdict_for(rule_action: str, conf: float, name: str, note: str | None, why_unsure: str | None = None,
                sugg: dict[str, Any] | None = None, asset_type: str = "stock", price: float | None = None) -> dict[str, Any]:
    """→ {action, label, conviction, headline, do, leaning}. Low conviction on a trade becomes HOLD, said plainly."""
    level = conviction(conf)
    sugg = sugg or {}
    pct = f"{conf * 100:.0f}%"
    if rule_action in TRADES and level == "low":
        lean = VERDICT[rule_action].lower()
        return {"action": "HOLD", "label": "Hold", "conviction": "low", "leaning": rule_action,
                "headline": f"Hold {name}",
                "do": f"Do nothing — keep holding. ({why_unsure or f'Signals lean {lean}, but only {pct} confident — not enough to act.'})"}
    label = VERDICT.get(rule_action, rule_action.title())
    if rule_action == "REVIEW":  # the data gates: say plainly that nothing should be traded on this yet
        return {"action": "REVIEW", "label": label, "conviction": "low", "leaning": None,
                "headline": f"Hold {name} — data missing", "do": do_line("REVIEW", "low", sugg, asset_type, price)}
    head = {"EXIT": f"Sell {name}" if level == "high" else f"Sell half of {name}",
            "TRIM": f"Sell some {name}", "ADD": f"Buy more {name}", "ACCUMULATE": f"Buy more {name}", "HOLD": f"Hold {name}",
            "SWITCH": f"Switch {name}", "REBALANCE": f"Rebalance {name}"}.get(rule_action, f"{label} {name}")
    return {"action": rule_action, "label": label, "conviction": level, "leaning": None, "headline": head,
            "do": do_line(rule_action, level, sugg, asset_type, price) if sugg or rule_action == "HOLD" else (note or "")}


def confidence(decision: Decision, facts: dict[str, Any], evidence: dict[str, Any], dq_mult: float) -> tuple[float, dict[str, Any]]:
    action = decision.rule.action
    signals = ((evidence.get("technical") or {}).get("signals") or [])
    direction = 1 if action in BULLISH else -1 if action in BEARISH else 0
    alignment = 1.0
    agree = total = 0
    if direction and signals:
        total = len(signals)
        agree = sum(1 for s in signals if s["bias"] == direction)
        alignment = 0.85 + 0.15 * agree / total
    c = min(0.95, decision.rule.base_confidence * dq_mult * alignment)
    return round(c, 2), {"base": decision.rule.base_confidence, "data_quality_multiplier": dq_mult,
                         "signal_alignment": round(alignment, 3), "signals_agreeing": agree, "signals_total": total}


def suggestion(action: str, row: dict[str, Any], facts: dict[str, Any], evidence: dict[str, Any], profile_value: float,
               rule: Any = None) -> dict[str, Any]:
    """Concrete, sized suggestion (never executed in P1 — shadow portfolio only)."""
    price = row.get("price")
    qty = row.get("quantity") or 0
    mv = row.get("market_value") or 0
    size = evidence.get("sizing") or {}
    cap = size.get("cap_pct")
    weight = size.get("weight_pct") or 0
    if action == "EXIT":
        return {"type": "sell", "quantity": qty, "value": mv, "note": "Sell the full position"}
    if action == "TRIM":
        rule_frac = getattr(rule, "trim_fraction", None)
        if rule_frac:  # e.g. a broken thesis: sell half now, the rest later if it doesn't recover
            frac = float(rule_frac)
        elif facts.get("pos.over_cap") and cap and weight:
            frac = 1 - cap / weight
        else:
            frac = 0.25
        q = math.floor(qty * frac) if row["asset_type"] in ("stock", "etf") else round(qty * frac, 3)
        note = (f"Sell {frac * 100:.0f}% now" if rule_frac else f"Sell ~{frac * 100:.0f}% to bring weight to {cap or weight * (1 - frac):.1f}%")
        return {"type": "sell", "quantity": q, "value": round(q * (price or 0), 2), "fraction": round(frac, 2), "note": note}
    if action in ("ADD", "ACCUMULATE"):
        room = max(0.0, (cap or weight + 2) - weight) / 100 * profile_value
        amount = min(room, profile_value * 0.02) if action == "ADD" else min(room, profile_value * 0.03)
        why = []
        risk_cap = size.get("add_value_at_1pct_risk")
        if risk_cap and risk_cap < amount:  # volatile stock: a smaller amount carries the same risk
            amount, why = risk_cap, ["sized so a 2×ATR fall costs ≤ 1% of the portfolio"]
        if facts.get("regime.caution"):  # correction / bear: keep buying quality, in smaller steps
            amount, why = amount / 2, [*why, "half size while the market is in a correction"]
        tranches = 3 if action == "ACCUMULATE" else 1
        return {"type": "buy", "value": round(amount, 2), "tranches": tranches,
                "quantity": math.floor(amount / price) if price and row["asset_type"] in ("stock", "etf") else None,
                "note": f"Deploy {inr(amount)}" + (f" in {tranches} tranches on weakness" if tranches > 1 else "") + (f" ({'; '.join(why)})" if why else "")}
    if action == "SWITCH":
        mf = evidence.get("fund") or {}
        excess = (mf.get("cost") or {}).get("excess_cost_pct") or (0.7 if facts.get("mf.is_regular") else 0)
        note = "Switch to the Direct plan of the same scheme" if facts.get("mf.is_regular") else "Switch to a consistent fund in the same category"
        wait = facts.get("tax.days_to_ltcg")
        staged = None
        if isinstance(wait, int | float) and 0 < wait <= 365:  # switching = selling: under a year means exit load + 20% STCG
            from datetime import date, timedelta

            when = (date.today() + timedelta(days=int(wait))).strftime("%d %b %Y")
            staged = when
            note = (f"Start new SIPs in the {'Direct plan' if facts.get('mf.is_regular') else 'new fund'} now; move the existing units after {when} "
                    "(after a year: usually no exit load, and 12.5% long-term tax instead of 20%)")
        return {"type": "switch", "value": mv, "annual_cost_saving": round(mv * max(excess, 0) / 100, 2), "note": note, "switch_after": staged}
    if action == "HOLD" and facts.get("trade.stop_price") and (facts.get("intent") == "trade" or getattr(rule, "id", "") == "euphoria_protect_gains"):
        return {"type": "trail_stop", "value": 0, "stop": facts["trade.stop_price"], "source": facts.get("trade.stop_source")}
    return {"type": "none", "value": 0}


def rupee_impact(action: str, row: dict[str, Any], sugg: dict[str, Any]) -> float:
    if action in ("EXIT", "TRIM", "ADD", "ACCUMULATE"):
        return float(sugg.get("value") or 0)
    if action == "SWITCH":
        return float(sugg.get("annual_cost_saving") or 0) * 10  # decade of avoided cost
    if action == "REVIEW":
        return float(row.get("market_value") or 0) * 0.2
    return 0.0


def reasons(decision: Decision, facts: dict[str, Any], evidence: dict[str, Any]) -> list[str]:
    out = [decision.rule.reason]
    dd = evidence.get("drawdown") or {}
    attr = dd.get("attribution")
    if dd.get("triggered"):
        ref = f"{dd['from_cost_pct']:+.1f}% from your cost" if dd.get("basis") == "cost" else f"{dd['from_high_pct']:+.1f}% from its 52-week high"
        line = f"Down {ref} (your alert level: {dd['threshold_pct']:.0f}%)"
        if attr:
            line += f" — market {attr['market_pct']:+.1f}%, sector {attr['sector_pct']:+.1f}%, company-specific {attr['stock_specific_pct']:+.1f}%"
        out.append(line)
    fund = evidence.get("fundamental") or {}
    if fund.get("available"):
        top = sorted(fund.get("metrics") or [], key=lambda m: m["score"])
        weak = [m for m in top if m["status"] == "weak"][:2]
        strong = [m for m in reversed(top) if m["status"] == "good"][:2]
        pick = weak if decision.rule.action in BEARISH | {"REVIEW"} else strong
        if pick:
            out.append(f"Fundamental score {fund['score']:.0f}/100: " + "; ".join(f"{m['label']} {m['value']}{m['unit'] if m['unit'] != 'x' else 'x'}" for m in pick))
    tech = evidence.get("technical") or {}
    if tech.get("available"):
        tv = tech["values"]
        out.append(f"Technical score {tech['score']:.0f}/100 ({tech['trend']}); RSI {tv.get('rsi14') or 0:.0f}; price vs 200-DMA ₹{tv.get('sma200') or 0:,.0f}")
    mf = evidence.get("fund") or {}
    if mf.get("available") and mf.get("score") is not None:
        bits = [f"Fund score {mf['score']:.0f}/100"]
        if mf.get("consistency_pct") is not None:
            bits.append(f"beat benchmark in {mf['consistency_pct']:.0f}% of rolling periods")
        if mf.get("alpha_pct") is not None:
            bits.append(f"alpha {mf['alpha_pct']:+.1f}%/yr")
        out.append(", ".join(bits))
    size = evidence.get("sizing") or {}
    if size.get("over_cap"):
        out.append(f"Weight {size['weight_pct']:.1f}% vs your cap {size['cap_pct']:.0f}%")
    return out[:4]


def what_would_change(action: str, facts: dict[str, Any], evidence: dict[str, Any]) -> str:
    tv = (evidence.get("technical") or {}).get("values") or {}
    levels = (evidence.get("technical") or {}).get("levels") or {}
    sma200 = tv.get("sma200")
    sup = (levels.get("support") or [None])[0]
    res = (levels.get("resistance") or [None])[0]
    if action == "EXIT":
        return f"Re-evaluate if price reclaims the 200-DMA (₹{sma200:,.0f}) with fundamental score back above 50." if sma200 else "Re-evaluate if fundamentals recover above 50/100."
    if action in ("ADD", "ACCUMULATE"):
        if sup:
            return f"Pause buying if it closes below support ₹{sup:,.0f} or the fundamental score drops below 50."
        return "Pause if the fund's rolling-return consistency falls below 50% or its cost rises."
    if action == "TRIM":
        return "Stop trimming once weight is back under your cap or momentum cools (RSI < 60)."
    if action == "SWITCH":
        return "Stay if the fund's 3-year consistency improves above 60% or exit load/tax cost exceeds one year of savings."
    if action == "HOLD":
        if sma200:
            return f"Would turn bearish on a close below the 200-DMA (₹{sma200:,.0f}) or a drawdown beyond {facts.get('dd.threshold', 20):.0f}%." + (f" Bullish above resistance ₹{res:,.0f}." if res else "")
        return "Would change if contributions stop, the rate changes, or your allocation drifts from target."
    return "Resolve the flagged issues and re-run the analysis."


def tax_line(action: str, evidence: dict[str, Any]) -> str | None:
    tax = evidence.get("tax") or {}
    if not tax.get("applicable"):
        return None
    if action in BEARISH | {"SWITCH"}:
        line = f"Selling now: est. tax {inr(tax['est_tax_if_sold_now'])} (ST gain {inr(tax['short_term_gain'])}, LT gain {inr(tax['long_term_gain'])})."
        if (evidence.get("position") or {}).get("dates_estimated"):
            line += " (Purchase dates are estimated from a holdings statement — short/long-term split may differ.)"
        guessed = bool((evidence.get("position") or {}).get("dates_estimated"))
        if tax.get("days_to_ltcg") is not None and (tax.get("saving_if_wait") or 0) > 500 and not guessed:
            wait_to = (date.today() + timedelta(days=tax["days_to_ltcg"])).strftime("%d %b %Y")
            line += f" Waiting {tax['days_to_ltcg']} days (till {wait_to}) turns the gain long-term and saves ~{inr(tax['saving_if_wait'])}."
        loss = min(tax["short_term_gain"], 0) + min(tax["long_term_gain"], 0)
        if loss < 0:
            line += (f" Booking this {inr(-loss)} capital loss can be set off against this FY's capital gains "
                     "(short-term losses against any gains, long-term only against long-term) and carried forward for 8 years.")
        return line
    if tax.get("long_term_gain", 0) > 0 and tax.get("equity_taxation"):
        return f"Unrealised long-term gain {inr(tax['long_term_gain'])} — part can be harvested tax-free within the ₹1.25 L/FY LTCG exemption."
    return None


def counter_arguments(action: str, evidence: dict[str, Any]) -> list[str]:
    direction = 1 if action in BULLISH else -1 if action in BEARISH else 0
    sigs = ((evidence.get("technical") or {}).get("signals") or [])
    out = [f"{s['label']} ({s['evidence']})" for s in sigs if direction and s["bias"] == -direction][:4]
    fund = evidence.get("fundamental") or {}
    if direction > 0:
        out += [f"Red flag: {f['message']}" for f in fund.get("red_flags") or []]
    elif direction < 0 and fund.get("score") and fund["score"] >= 60:
        out.append(f"Fundamentals are still decent (score {fund['score']:.0f}/100) — the business may recover.")
    regime = evidence.get("regime") or {}
    if direction < 0 and regime.get("regime") in ("correction", "bear"):
        out.append(f"Market regime is '{regime['regime']}': selling into broad weakness often locks in temporary losses.")
    return out


def scenario(row: dict[str, Any], evidence: dict[str, Any]) -> list[dict[str, Any]]:
    beta = ((evidence.get("market_beta") or {}).get("beta")) or (1.0 if row["asset_type"] in ("stock", "etf") else 0.9 if row["asset_type"] == "mutual_fund" else 0.0)
    mv = row.get("market_value") or 0
    return [{"scenario": f"NIFTY {s:+d}%", "estimated_change": round(mv * beta * s / 100, 2), "estimated_value": round(mv * (1 + beta * s / 100), 2)}
            for s in (-20, -10, 10)] + [{"scenario": "beta used", "value": beta}]


def build(
    *, decision: Decision, row: dict[str, Any], facts: dict[str, Any], evidence: dict[str, Any], scores: dict[str, Any], intent: str,
    intent_note: str, rulebook_version: str, profile_value: float, profile_name: str | None, history: list[dict[str, Any]],
) -> dict[str, Any]:
    dq = evidence.get("data_quality") or {}
    from .facts import DQ_MULT

    conf, conf_detail = confidence(decision, facts, evidence, DQ_MULT.get(dq.get("grade", "B"), 0.9))
    action = decision.rule.action
    sugg = suggestion(action, row, facts, evidence, profile_value, decision.rule)
    impact = rupee_impact(action, row, sugg)
    why = reasons(decision, facts, evidence)
    tax = tax_line(action, evidence)
    change = what_would_change(action, facts, evidence)
    rule_sugg = dict(sugg)
    v = verdict_for(action, conf, row.get("name") or row["symbol"], sugg.get("note"), sugg=sugg, asset_type=row["asset_type"], price=row.get("price"))
    headline = v["headline"]
    if v["action"] != action:  # not sure enough to trade: hold, and say what would make it a call
        sugg = {"type": "none", "note": None}
        impact = 0.0
        tax = None
        change = f"A clearer {VERDICT[action].lower()} signal: {change[0].lower()}{change[1:]}" if change else change
    ih = input_hash(facts, rulebook_version)
    short = {
        "action": v["action"], "rule_action": action, "rule_suggestion": rule_sugg, "rules_confidence": conf, "verdict": v["label"], "conviction": v["conviction"], "leaning": v["leaning"], "do": v["do"],
        "asset_type": row["asset_type"], "price": row.get("price"),
        "horizon": decision.rule.horizon, "intent": intent, "confidence": conf, "headline": headline,
        "reasons": why[:3], "tax_impact": tax, "what_would_change": change, "suggestion": sugg, "rupee_impact": round(impact, 2),
        "urgent": decision.rule.urgent and v["conviction"] == "high", "data_quality": {"grade": dq.get("grade"), "score": dq.get("score")},
        "composite_score": scores["composite"]["score"],
    }
    full = {
        "summary": {**short, "all_reasons": why, "profile": profile_name, "symbol": row["symbol"], "name": row.get("name"),
                    "asset_type": row["asset_type"], "intent_explanation": intent_note},
        "evidence": {
            "position": evidence["position"],
            "technical": {k: v for k, v in (evidence.get("technical") or {}).items() if k != "series"},
            "chart_series": (evidence.get("technical") or {}).get("series"),
            "fundamental": evidence.get("fundamental"), "fund": evidence.get("fund"), "risk": evidence.get("risk"),
            "market_beta": evidence.get("market_beta"), "drawdown": evidence.get("drawdown"), "sizing": evidence.get("sizing"),
            "tax": evidence.get("tax"), "thesis": evidence.get("thesis"), "regime": evidence.get("regime"),
            "quote": evidence.get("quote"), "benchmark_symbol": evidence.get("benchmark_symbol"),
        },
        "data_quality": dq,
        "decision_trace": {
            "rulebook_version": rulebook_version, "matched_rule": decision.rule.id, "rules_evaluated": decision.trace,
            "facts": facts, "dimension_scores": scores["dimensions"], "composite": scores["composite"], "confidence": conf_detail,
        },
        "risks_and_counter_arguments": counter_arguments(action, evidence),
        "dates_note": (evidence.get("position") or {}).get("note"),
        "scenario": scenario(row, evidence),
        "history": history,
        "input_hash": ih,
        "disclaimer": DISCLAIMER,
    }
    return {"short": short, "full": full, "confidence": conf, "impact": impact, "headline": headline, "input_hash": ih,
            "action": v["action"], "urgent": short["urgent"]}
