"""service tables (auth, core, market, advisor) — autogenerated from each service's models

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 12:50:18.431909
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_hint', sa.String(length=12), nullable=True),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('monthly_budget_usd', sa.Float(), server_default='10', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_providers')),
    sa.UniqueConstraint('household_id', 'provider', name='uq_ai_provider'),
    schema='advisor'
    )
    op.create_table('runs',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('scope', sa.String(length=40), server_default='household', nullable=False),
    sa.Column('rulebook_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('regime', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs')),
    schema='advisor'
    )
    op.create_index(op.f('ix_advisor_runs_household_id'), 'runs', ['household_id'], unique=False, schema='advisor')
    op.create_table('households',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('plan', sa.String(length=40), server_default='free', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_households')),
    sa.UniqueConstraint('slug'),
    schema='auth'
    )
    op.create_table('profile_groups',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('profile_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_groups')),
    schema='core'
    )
    op.create_index(op.f('ix_core_profile_groups_household_id'), 'profile_groups', ['household_id'], unique=False, schema='core')
    op.create_table('profiles',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('relationship', sa.Enum('self', 'spouse', 'parent', 'child', 'sibling', 'huf', 'other', name='relationship', schema='core'), server_default='self', nullable=False),
    sa.Column('linked_user_id', sa.UUID(), nullable=True),
    sa.Column('pan_encrypted', sa.Text(), nullable=True),
    sa.Column('pan_last4', sa.String(length=4), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('tax_slab_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_profile', sa.Enum('conservative', 'moderate', 'aggressive', name='risk_profile', schema='core'), server_default='moderate', nullable=False),
    sa.Column('retirement_age', sa.Integer(), server_default='60', nullable=False),
    sa.Column('target_allocation', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('drawdown_thresholds', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    schema='core'
    )
    op.create_index('ix_profiles_household', 'profiles', ['household_id'], unique=False, schema='core')
    op.create_table('instruments',
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('stock', 'etf', 'mutual_fund', 'nps', 'epf', 'vpf', 'ppf', 'bond', 'fixed_deposit', 'gold', 'reit', 'crypto', 'index', 'cash', name='asset_type', schema='market'), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('benchmark_symbol', sa.String(length=64), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments')),
    sa.UniqueConstraint('symbol', 'asset_type', 'household_id', name='uq_instruments_symbol_type_household', postgresql_nulls_not_distinct=True),
    schema='market'
    )
    op.create_index('ix_instruments_isin', 'instruments', ['isin'], unique=False, schema='market')
    op.create_index('ix_instruments_name_lower', 'instruments', [sa.text('lower(name)')], unique=False, schema='market')
    op.create_index('ix_instruments_symbol', 'instruments', ['symbol'], unique=False, schema='market')
    op.create_table('recommendations',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('subject_key', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.String(length=24), nullable=True),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('horizon', sa.String(length=12), nullable=False),
    sa.Column('intent', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.Float(), server_default='0', nullable=False),
    sa.Column('bucket', sa.String(length=12), server_default='fyi', nullable=False),
    sa.Column('actionable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('rupee_impact', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('short_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('full_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('rulebook_version', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('price_at_call', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('benchmark_at_call', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('ai_consensus', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('snooze_until', sa.Date(), nullable=True),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acted_by', sa.UUID(), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['advisor.runs.id'], name=op.f('fk_recommendations_run_id_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations')),
    schema='advisor'
    )
    op.create_index('ix_recs_household_status', 'recommendations', ['household_id', 'status'], unique=False, schema='advisor')
    op.create_index('ix_recs_subject', 'recommendations', ['household_id', 'subject_key'], unique=False, schema='advisor')
    op.create_table('users',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'advisor', 'member', 'viewer', 'service', name='user_role', schema='auth'), server_default='member', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('oidc_provider', sa.String(length=50), nullable=True),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['auth.households.id'], name=op.f('fk_users_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('oidc_provider', 'oidc_subject', name='uq_users_oidc_identity'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_household_id'), 'users', ['household_id'], unique=False, schema='auth')
    op.create_index('ix_users_email_lower', 'users', [sa.text('lower(email)')], unique=True, schema='auth')
    op.create_table('holding_prefs',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('intent', sa.Enum('core', 'satellite', 'trade', 'retirement', 'goal', name='holding_intent', schema='core'), nullable=True),
    sa.Column('intent_source', sa.String(length=10), server_default='auto', nullable=False),
    sa.Column('goal_name', sa.String(length=120), nullable=True),
    sa.Column('thesis', sa.Text(), server_default='', nullable=False),
    sa.Column('thesis_checks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('drawdown_threshold_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['core.profiles.id'], name=op.f('fk_holding_prefs_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holding_prefs')),
    sa.UniqueConstraint('profile_id', 'instrument_id', name='uq_holding_prefs'),
    schema='core'
    )
    op.create_index(op.f('ix_core_holding_prefs_household_id'), 'holding_prefs', ['household_id'], unique=False, schema='core')
    op.create_table('portfolios',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('broker', 'mutual_funds', 'retirement', 'deposits', 'other', name='portfolio_kind', schema='core'), server_default='broker', nullable=False),
    sa.Column('broker', sa.String(length=60), nullable=True),
    sa.Column('base_currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['core.profiles.id'], name=op.f('fk_portfolios_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios')),
    schema='core'
    )
    op.create_index('ix_portfolios_household_profile', 'portfolios', ['household_id', 'profile_id'], unique=False, schema='core')
    op.create_table('profile_access',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('read', 'write', name='access_level', schema='core'), server_default='write', nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['core.profiles.id'], name=op.f('fk_profile_access_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'user_id', name=op.f('pk_profile_access')),
    schema='core'
    )
    op.create_table('corporate_actions',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('split', 'bonus', 'dividend', 'merger', 'demerger', name='corporate_action_type', schema='market'), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('ratio_from', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ratio_to', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('source', sa.String(length=32), server_default='provider', nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['market.instruments.id'], name=op.f('fk_corporate_actions_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corporate_actions')),
    sa.UniqueConstraint('instrument_id', 'action_type', 'ex_date', name='uq_corp_action'),
    schema='market'
    )
    op.create_index(op.f('ix_market_corporate_actions_ex_date'), 'corporate_actions', ['ex_date'], unique=False, schema='market')
    op.create_index(op.f('ix_market_corporate_actions_instrument_id'), 'corporate_actions', ['instrument_id'], unique=False, schema='market')
    op.create_table('fundamentals',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['market.instruments.id'], name=op.f('fk_fundamentals_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_fundamentals')),
    schema='market'
    )
    op.create_table('prices_eod',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=32), server_default='provider', nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['market.instruments.id'], name=op.f('fk_prices_eod_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'price_date', name=op.f('pk_prices_eod')),
    schema='market'
    )
    op.create_table('ai_reviews',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('stance', sa.String(length=12), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('rationale', sa.Text(), server_default='', nullable=False),
    sa.Column('counter_case', sa.Text(), server_default='', nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['advisor.recommendations.id'], name=op.f('fk_ai_reviews_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_reviews')),
    schema='advisor'
    )
    op.create_index('ix_ai_reviews_rec', 'ai_reviews', ['recommendation_id'], unique=False, schema='advisor')
    op.create_table('recommendation_outcomes',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('evaluated_on', sa.Date(), nullable=False),
    sa.Column('price_then', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('price_now', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('benchmark_return_pct', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['advisor.recommendations.id'], name=op.f('fk_recommendation_outcomes_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id', 'horizon_days', name=op.f('pk_recommendation_outcomes')),
    schema='advisor'
    )
    op.create_index(op.f('ix_advisor_recommendation_outcomes_household_id'), 'recommendation_outcomes', ['household_id'], unique=False, schema='advisor')
    op.create_table('shadow_trades',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('qty_delta', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('executed_on', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['advisor.recommendations.id'], name=op.f('fk_shadow_trades_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shadow_trades')),
    schema='advisor'
    )
    op.create_index(op.f('ix_advisor_shadow_trades_household_id'), 'shadow_trades', ['household_id'], unique=False, schema='advisor')
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=16), server_default='web', nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False, schema='auth')
    op.create_table('applied_corporate_actions',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('corporate_action_id', sa.UUID(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['core.portfolios.id'], name=op.f('fk_applied_corporate_actions_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portfolio_id', 'corporate_action_id', name=op.f('pk_applied_corporate_actions')),
    schema='core'
    )
    op.create_table('import_jobs',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['core.portfolios.id'], name=op.f('fk_import_jobs_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs')),
    schema='core'
    )
    op.create_index(op.f('ix_core_import_jobs_household_id'), 'import_jobs', ['household_id'], unique=False, schema='core')
    op.create_table('portfolio_snapshots',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('invested', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('is_complete', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['core.portfolios.id'], name=op.f('fk_portfolio_snapshots_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portfolio_id', 'snapshot_date', name=op.f('pk_portfolio_snapshots')),
    schema='core'
    )
    op.create_index(op.f('ix_core_portfolio_snapshots_household_id'), 'portfolio_snapshots', ['household_id'], unique=False, schema='core')
    op.create_table('transactions',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('asset_type', sa.String(length=24), nullable=False),
    sa.Column('txn_type', sa.Enum('buy', 'sell', 'sip', 'dividend', 'interest', 'contribution', 'withdrawal', 'split', 'bonus', 'switch_in', 'switch_out', 'fee', name='txn_type', schema='core'), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), server_default='0', nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), server_default='0', nullable=False),
    sa.Column('fees', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('source', sa.String(length=64), server_default='manual', nullable=False),
    sa.Column('client_ref', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['core.portfolios.id'], name=op.f('fk_transactions_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('portfolio_id', 'client_ref', name='uq_transactions_client_ref'),
    schema='core'
    )
    op.create_index('ix_transactions_household_updated', 'transactions', ['household_id', 'updated_at'], unique=False, schema='core')
    op.create_index('ix_transactions_instrument', 'transactions', ['instrument_id'], unique=False, schema='core')
    op.create_index('ix_transactions_portfolio_date', 'transactions', ['portfolio_id', 'trade_date'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_portfolio_date', table_name='transactions', schema='core')
    op.drop_index('ix_transactions_instrument', table_name='transactions', schema='core')
    op.drop_index('ix_transactions_household_updated', table_name='transactions', schema='core')
    op.drop_table('transactions', schema='core')
    op.drop_index(op.f('ix_core_portfolio_snapshots_household_id'), table_name='portfolio_snapshots', schema='core')
    op.drop_table('portfolio_snapshots', schema='core')
    op.drop_index(op.f('ix_core_import_jobs_household_id'), table_name='import_jobs', schema='core')
    op.drop_table('import_jobs', schema='core')
    op.drop_table('applied_corporate_actions', schema='core')
    op.drop_index(op.f('ix_auth_refresh_tokens_user_id'), table_name='refresh_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_refresh_tokens_family_id'), table_name='refresh_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_refresh_tokens_expires_at'), table_name='refresh_tokens', schema='auth')
    op.drop_table('refresh_tokens', schema='auth')
    op.drop_index(op.f('ix_advisor_shadow_trades_household_id'), table_name='shadow_trades', schema='advisor')
    op.drop_table('shadow_trades', schema='advisor')
    op.drop_index(op.f('ix_advisor_recommendation_outcomes_household_id'), table_name='recommendation_outcomes', schema='advisor')
    op.drop_table('recommendation_outcomes', schema='advisor')
    op.drop_index('ix_ai_reviews_rec', table_name='ai_reviews', schema='advisor')
    op.drop_table('ai_reviews', schema='advisor')
    op.drop_table('prices_eod', schema='market')
    op.drop_table('fundamentals', schema='market')
    op.drop_index(op.f('ix_market_corporate_actions_instrument_id'), table_name='corporate_actions', schema='market')
    op.drop_index(op.f('ix_market_corporate_actions_ex_date'), table_name='corporate_actions', schema='market')
    op.drop_table('corporate_actions', schema='market')
    op.drop_table('profile_access', schema='core')
    op.drop_index('ix_portfolios_household_profile', table_name='portfolios', schema='core')
    op.drop_table('portfolios', schema='core')
    op.drop_index(op.f('ix_core_holding_prefs_household_id'), table_name='holding_prefs', schema='core')
    op.drop_table('holding_prefs', schema='core')
    op.drop_index('ix_users_email_lower', table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_household_id'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_index('ix_recs_subject', table_name='recommendations', schema='advisor')
    op.drop_index('ix_recs_household_status', table_name='recommendations', schema='advisor')
    op.drop_table('recommendations', schema='advisor')
    op.drop_index('ix_instruments_symbol', table_name='instruments', schema='market')
    op.drop_index('ix_instruments_name_lower', table_name='instruments', schema='market')
    op.drop_index('ix_instruments_isin', table_name='instruments', schema='market')
    op.drop_table('instruments', schema='market')
    op.drop_index('ix_profiles_household', table_name='profiles', schema='core')
    op.drop_table('profiles', schema='core')
    op.drop_index(op.f('ix_core_profile_groups_household_id'), table_name='profile_groups', schema='core')
    op.drop_table('profile_groups', schema='core')
    op.drop_table('households', schema='auth')
    op.drop_index(op.f('ix_advisor_runs_household_id'), table_name='runs', schema='advisor')
    op.drop_table('runs', schema='advisor')
    op.drop_table('ai_providers', schema='advisor')
    # ### end Alembic commands ###
